name: "Safe Explorer"
help: 'Pytorch implementation of "Safe Exploration in Continuous Action Spaces".'
arguments:
  - name: "env"
    help: "Configuration related to simulation environments."
    properties:
      - name: "ballnd"
        help: "Ball-ND environment configuration."
        properties:
          - name: "n"
            default: 1
          - name: "target_margin"
            default: 0.2
          - name: "agent_slack"
            default: 0.1
          - name: "episode_length"
            default: 30
          - name: "time_step"
            default: 0.1
          - name: "respawn_interval"
            default: 2
          - name: "target_noise_std"
            default: 0.05
          - name: "enable_reward_shaping"
            default: false
          - name: "reward_shaping_slack"
            default: 0.14 # 1d: 0.14; 3d: 0.2          
  - name: "ddpg"
    help: "Hyperparameters for DDPG algorithm."
    properties:
    - name: "actor"
      help: "Actor network parameters."
      properties:
        - name: "layers"
          default: [100, 100]
    - name: "critic"
      help: "Critic network parameters."
      properties:
        - name: "layers"
          default: [500, 500]
    - name: "trainer"
      help: "Training parameters."
      properties:
        - name: "epochs"
          default: 300
        - name: "training_steps_per_epoch"
          default: 1000
        - name: "training_episodes_per_epoch"
          default: 1 # 20
        - name: "evaluation_episodes_per_epoch"
          default: 1 # 5
        - name: "batch_size"
          default: 256
        - name: "max_episode_length"
          default: 500 # 300
        - name: "replay_buffer_size"
          default: 1000000
        - name: "discount_factor"
          default: 0.99
        - name: "tau"
          default: 0.001
        - name: "actor_lr"
          default: 0.001 # 0.0001
        - name: "critic_lr"
          default: 0.001
        - name: "action_noise_range"
          default: 0.01
        - name: "reward_scale"
          default: 1
  - name: "safety_layer"
    help: "Safety layer configuration."
    properties:
      - name: "constraint_model"
        help: "Hyperparameters for constraint model (g)"
        properties:
          - name: "layers"
            default: [10]
      - name: "trainer"
        help: "Constraint model training parameters"
        properties:
          - name: "batch_size"
            default: 256
          - name: "lr"
            default: 0.0001
          - name: "max_episode_length"
            default: 500 # 300
          - name: "epochs"
            default: 25
          - name: "training_steps_per_epoch"
            default: 1000
          - name: "evaluation_steps_per_epoch"
            default: 20
          - name: "replay_buffer_size"
            default: 1000000
          - name: "sample_data_episodes"
            default: 1000
  - name: "main"
    help: "Safe-Explorer driver properties."
    properties:
      - name: "trainer"
        help: "Training configuration."
        properties:
          - name: "seed"
            default: 0
          - name: "task"
            default: "ballnd"
          - name: "use_safety_layer"
            default: false
